#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import gtk
import apt_pkg
import sys
import os
from peak_common import Peak
from peak_common import Peak_tree

class Package:
    def __init__(self, pkg_dict, pkg):
        self.pkg = pkg
        self.is_peak = False
        self.is_confirmed = False
        self.is_removable = False
        pkg_dict[pkg.id] = self

class GPeak (object):

    def __init__(self):
        self.builder = gtk.Builder()
        glade_file = "apt-peak.glade"
        if not os.path.exists(glade_file):
            glade_file = "/usr/share/apt-peak/glade/apt-peak.glade"
        self.builder.add_from_file(glade_file)
        self.builder.connect_signals(self)

    def list_orphans(self):

        peak = Peak(self.cache)

        for otherpkg in self.cache.packages:
            if peak.is_peak(otherpkg):
                package = Package(self.packages, otherpkg)
                package.is_peak = True

    def pcolor(self, package):
        if not package.is_peak:
            return "#000088"
        if package.is_confirmed:
            return "#008800"
        if package.is_removable:
            return "#880000"
        return "#000000"


    def update_confirmed_list(self):
        self.confirmed_liststore.clear()
        for pkgid, package in self.packages.items():
            if package.is_confirmed:
                self.confirmed_liststore.append([package.pkg.get_fullname(True), self.pcolor(package), pkgid])

    def update_peak_list(self):
        self.peak_liststore.clear()
        for pkgid, package in self.packages.items():
            if package.is_peak and not package.is_confirmed:
                self.peak_liststore.append([package.pkg.get_fullname(True), self.pcolor(package), pkgid])

    def update_removable_list(self):
        self.removable_liststore.clear()
        for pkgid, package in self.packages.items():
            if package.is_removable:
                self.removable_liststore.append([package.pkg.get_fullname(True), self.pcolor(package), pkgid])

    def update_lists(self):
        self.update_confirmed_list()
        self.update_peak_list()
        self.update_removable_list()
        self.perform_remove.set_sensitive(False)

    def init_gui_objects(self):
        self.confirmed = self.builder.get_object("confirmed")
        self.confirmed.get_selection().set_mode(gtk.SELECTION_MULTIPLE)

        self.peak = self.builder.get_object("peak")
        self.peak.get_selection().set_mode(gtk.SELECTION_MULTIPLE)

        self.removable = self.builder.get_object("removable")
        self.removable.get_selection().set_mode(gtk.SELECTION_MULTIPLE)

        self.confirmed_liststore = self.builder.get_object("confirmed_liststore")
        self.confirmed_liststore.set_sort_column_id(0, gtk.SORT_ASCENDING)

        self.peak_liststore = self.builder.get_object("peak_liststore")
        self.peak_liststore.set_sort_column_id(0, gtk.SORT_ASCENDING)

        self.removable_liststore = self.builder.get_object("removable_liststore")
        self.removable_liststore.set_sort_column_id(0, gtk.SORT_ASCENDING)

        self.perform_remove = self.builder.get_object("perform_remove")

    def confirm_package(self, package, conf_value):
        package.is_confirmed = conf_value
        if conf_value:
            self.confirmed_set.add(package.pkg.get_fullname(True))
            package.is_removable = False
        else:
            self.confirmed_set.remove(package.pkg.get_fullname(True))
            if not package.is_peak:
                package.is_removable = True

    def confirm(self, *args):
        conf_value = False
        treeview = None
        if args[0].get_label() == "<< Confirm":
            treeview = self.peak
            conf_value = True
        if args[0].get_label() == "Unconfirm >>":
            treeview = self.confirmed
            conf_value = False
        if args[0].get_label() == "Move to confirmed >>":
            treeview = self.removable
            conf_value = True

        treemodel, paths = treeview.get_selection().get_selected_rows()
        for path in paths:
            package = self.packages[treemodel[path][2]]
            self.confirm_package(package, conf_value)
        self.update_lists()

    def remove(self, *args):
        treemodel, paths = self.peak.get_selection().get_selected_rows()
        for path in paths:
            package = self.packages[treemodel[path][2]]
            package.is_removable = True
        self.update_lists()

    def clear_removables(self, *args):
        not_peak = list()

        for pkgid, package in self.packages.items():
            if package.is_removable:
                if package.is_peak:
                    package.is_removable = False
                else:
                    not_peak.append(pkgid)

        for pkgid in not_peak:
            self.packages.pop(pkgid)
        self.update_lists()


    def add_confirm_set(self):
        not_package = list()
        for package_name in self.confirmed_set:
            try:
                pkg = self.cache[package_name]
                if pkg.id in self.packages:
                    package = self.packages[pkg.id]
                else:
                    package = Package(self.packages, pkg)
                package.is_confirmed = True

            except KeyError as e:
                print("Package not found:", str(e).strip('"'), file=sys.stderr)
                not_package.append(package_name)
        for package_name in not_package:
            self.confirmed_set.remove(package_name)

    def add_peak_tree(self, *args):
        remove = list()
        keep = list()
        not_peak = list()
        peak_tree = Peak_tree(self.cache)

        for pkgid, package in self.packages.items():
            if package.is_removable:
                if package.is_peak:
                    remove.append(package.pkg)
                else:
                    not_peak.append(pkgid)
            if package.is_confirmed:
                    keep.append(package.pkg)

        for pkgid in not_peak:
            self.packages.pop(pkgid)

        if len(remove) == 0:
            self.update_lists()
            return
        removable = list()
        peak_tree.get_peak_tree(remove, keep, removable)

        for pkg in removable:
            if pkg.id in self.packages:
                package = self.packages[pkg.id]
            else:
                package = Package(self.packages, pkg)
            package.is_removable = True
        self.update_lists()
        self.perform_remove.set_sensitive(True)

    def refresh(self, *args):
        self.packages = dict()
        self.cache = apt_pkg.Cache()
        print("Search peak packages...", end="")
        sys.stdout.flush()
        self.list_orphans()
        print(" Done")
        sys.stdout.flush()

        self.add_confirm_set()

        self.update_lists()

    def run(self):
        self.builder.get_object("gapt_peak").show_all()
        self.init_gui_objects()
        self.load_confirm_set()

        self.refresh()
        gtk.main()

    def click_perform_remove(self, *args):
        remove = list()
        for pkgid, package in self.packages.items():
            if package.is_removable:
                remove.append(package.pkg.get_fullname(True))
        stream = os.popen("x-terminal-emulator -e sudo apt-get purge " + " ".join(remove))
        stream.read()
        stream.close()


    def load_confirm_set(self):
        load_file = os.path.expanduser("~/.config/apt-peak/confirmed.list")
        self.confirmed_set = set()
        if not os.path.exists(load_file):
            load_file = os.path.expanduser("~/.config/packet-peak/confirmed.list")
            if not os.path.exists(load_file):
                return
        with open(load_file, 'r') as f:
            lines = f.readlines()
        [self.confirmed_set.add(e.strip()) for e in lines]

    def save_confirm_set(self):
        save_dir = os.path.expanduser("~/.config/apt-peak")
        if not os.path.exists(save_dir):
            os.makedirs(save_dir)
        outfile = open(save_dir + "/confirmed.list", 'w')
        outfile.write("\n".join(self.confirmed_set))
        outfile.close()

    def on_window1_destroy(self, *args):
        self.save_confirm_set()
        gtk.main_quit()


apt_pkg.init()
GPeak().run()
